In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

C:\Users\RITURAJ CHANDA\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [10]:
# Load the dataset
file_path = "../Data/HAR1.csv"
df = pd.read_csv(file_path)

In [11]:
df.head()

,Acc-X,Acc-Y,Acc-Z,AG-X,AG-Y,AG-Z,Gravity-X,Gravity-Y,Gravity-Z,RR-X,RR-Y,RR-Z,RV-X,RV-Y,RV-Z,activity
0,-0.021284,0.044265,-0.140155,-0.146046,-1.501164,9.555558,-0.124762,-1.449662,9.698108,-0.015730,0.001833,-0.017181,-0.054314,0.050834,-0.616496,Sitting
1,0.005765,-0.129824,-0.112352,-0.129287,-1.649605,9.641749,-0.123081,-1.491051,9.691853,-0.027336,0.014050,0.002978,-0.056021,0.052551,-0.619921,Sitting
2,-0.134727,-0.071031,-0.087657,-0.282516,-1.596933,9.574712,-0.164548,-1.537872,9.683917,0.004429,0.016493,0.013363,-0.055781,0.056936,-0.621608,Sitting
3,0.058022,-0.029364,-0.139784,-0.126893,-1.546654,9.603442,-0.213646,-1.565174,9.678583,0.005651,0.002443,0.040241,-0.055755,0.058472,-0.622336,Sitting
4,0.120001,0.259513,-0.096766,-0.067038,-1.204284,9.569923,-0.175068,-1.478162,9.693027,0.006872,0.017104,0.034132,-0.053506,0.054132,-0.621781,Sitting

In [12]:
df.shape

(57070, 16)

In [13]:
# Separate features (X) and target variable (y)
X = df.drop('activity', axis=1)
y = df['activity']

In [14]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# Standardize the features (optional, but often recommended)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
# Convert NumPy arrays back to Pandas DataFrames
X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)

In [19]:
# Encode the target variable (convert activity labels to numerical values)
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

In [21]:
# Save the preprocessed data to new CSV files
# ../Data/HAR1.csv
X_train_df.to_csv("../Data/X_train_cleaned.csv", index=False)
X_test_df.to_csv("../Data/X_test_cleaned.csv", index=False)
pd.DataFrame(y_train, columns=['activity']).to_csv("../Data/y_train_cleaned.csv", index=False)
pd.DataFrame(y_test, columns=['activity']).to_csv("../Data/y_test_cleaned.csv", index=False)

In [24]:
# See CLeaned Data
path_Xtrain="../Data/X_train_cleaned.csv"
df_Xtrain = pd.read_csv(path_Xtrain)

In [25]:
df_Xtrain.head()

,Acc-X,Acc-Y,Acc-Z,AG-X,AG-Y,AG-Z,Gravity-X,Gravity-Y,Gravity-Z,RR-X,RR-Y,RR-Z,RV-X,RV-Y,RV-Z
0,0.025702,-0.033595,0.067506,-0.508272,-0.608640,1.238801,-0.956646,-1.043303,1.453969,0.005625,0.020220,-0.019911,-0.591680,0.276162,-0.473666
1,0.339861,-0.398468,0.891414,0.260174,0.055950,-0.299687,-0.077194,0.666149,-1.233151,-0.610077,0.544357,-1.017481,1.353296,1.059141,0.805135
2,-0.328516,0.318888,1.050660,-0.047198,0.644668,-0.270800,1.126323,0.635848,-1.037962,-0.716793,0.605692,-0.387576,0.211194,1.736544,1.480583
3,0.731908,-0.149654,-0.432827,0.253564,0.245788,-0.523720,-0.791885,0.662229,-0.296590,0.141978,-2.239823,-0.675244,0.003502,1.500226,1.443477
4,0.894002,-0.341949,-1.062218,1.018238,0.127773,-1.407590,0.412155,0.713922,-0.822206,0.002809,0.826707,-0.030414,0.348623,-0.058648,0.229526

In [26]:
path_Xtest="../Data/X_test_cleaned.csv"
df_Xtest = pd.read_csv(path_Xtest)
df_Xtest.head()

,Acc-X,Acc-Y,Acc-Z,AG-X,AG-Y,AG-Z,Gravity-X,Gravity-Y,Gravity-Z,RR-X,RR-Y,RR-Z,RV-X,RV-Y,RV-Z
0,0.026218,-0.039448,0.057697,-0.078146,-0.641912,1.177844,-0.182597,-1.072375,1.502291,0.002513,0.015492,-0.023163,-0.736083,0.201582,0.676583
1,-2.460964,-0.459899,2.153169,-2.190914,-0.918775,0.298700,-0.024152,0.628253,-1.376431,0.603234,-1.264121,0.830183,1.009857,1.486315,1.002788
2,0.059880,-0.051260,0.073244,0.213302,0.270537,0.157107,0.315039,0.559688,0.147383,-0.015976,-0.003037,-0.017429,0.167744,-0.950360,-1.031900
3,0.026725,-0.033758,0.080221,-0.521799,-0.616870,1.242336,-0.962743,-1.042996,1.453318,0.004201,0.015779,-0.032313,-0.590248,0.277222,-0.476243
4,-0.168975,-0.335047,0.389118,1.378491,0.050736,-0.202010,2.575391,0.366083,-0.746647,0.251950,0.063623,-0.994546,-1.145977,-1.597247,-1.004376

In [27]:
path_ytest="../Data/y_train_cleaned.csv"
df_ytest = pd.read_csv(path_ytest)
df_ytest.head()

   activity
0         2
1         1
2         5
3         1
4         5